/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package notaufnahmedb;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jens
 */
public class AnmeldekraftForm extends javax.swing.JFrame {
  
  private DBConnectionManager dBConnection;
   Connection dbcon;
   Queries query;

 
  public AnmeldekraftForm(DBConnectionManager dBConnection) throws SQLException{
    initComponents();
    this.dBConnection = dBConnection;
    this.query = new Queries(dBConnection);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    kknr = new javax.swing.JTextField();
    Nachname = new javax.swing.JTextField();
    Vorname = new javax.swing.JTextField();
    Strasse = new javax.swing.JTextField();
    plz = new javax.swing.JTextField();
    ort = new javax.swing.JTextField();
    Telefon = new javax.swing.JTextField();
    KKNR_pruefen = new javax.swing.JButton();
    Patient_anlegen = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    birthday = new javax.swing.JTextField();
    krankenkasse_label = new javax.swing.JLabel();
    krankenkasse = new javax.swing.JTextField();
    Abbrechen = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(204, 51, 255));

    jLabel1.setText("KK-Nr.:");

    jLabel2.setText("Nachname:");

    jLabel3.setText("Vorname:");

    jLabel4.setText("Straße:");

    jLabel5.setText("Postleitzahl:");

    jLabel6.setText("Ort:");

    jLabel7.setText("Telefon:");

    kknr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        kknrActionPerformed(evt);
      }
    });

    Nachname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        NachnameActionPerformed(evt);
      }
    });

    Vorname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VornameActionPerformed(evt);
      }
    });

    KKNR_pruefen.setText("<< Prüfen");
    KKNR_pruefen.setActionCommand("KKNr_pruefen");
    KKNR_pruefen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        KKNR_pruefenActionPerformed(evt);
      }
    });

    Patient_anlegen.setText("Patient anlegen >>");
    Patient_anlegen.setActionCommand("PatientAnlegen");
    Patient_anlegen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        Patient_anlegenActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
    jLabel8.setText("Notaufnahme InformationsSystem");

    jLabel9.setText("Geb. Datum:");

    krankenkasse_label.setText("Krankenkasse:");

    Abbrechen.setText("Abbrechen");
    Abbrechen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AbbrechenActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addComponent(jLabel2)
                  .addComponent(jLabel3)
                  .addComponent(jLabel6)
                  .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(krankenkasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(Nachname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(Vorname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(Telefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(birthday, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(Strasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(plz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(ort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kknr, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(krankenkasse_label)
                  .addComponent(jLabel9)
                  .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(KKNR_pruefen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(Abbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Patient_anlegen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(40, 40, 40))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(kknr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(KKNR_pruefen))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(krankenkasse_label)
          .addComponent(krankenkasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Vorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(Strasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(plz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(ort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7)
          .addComponent(Patient_anlegen)
          .addComponent(Abbrechen))
        .addContainerGap(50, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void VornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VornameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_VornameActionPerformed

  private void KKNR_pruefenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KKNR_pruefenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_KKNR_pruefenActionPerformed

  private void Patient_anlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_anlegenActionPerformed
    //String Knr = KKNR.getText();
    String Vname = Vorname.getText();
    String Name = Nachname.getText();
    String pLZ = plz.getText();
    String street = Strasse.getText();
    String place = ort.getText();
    String date = birthday.getText();
    String krk = krankenkasse.getText();
    String krknr = kknr.getText();
    String tel = Telefon.getText();
    

    if (Vname.isEmpty() == true || Name.isEmpty() == true || pLZ.isEmpty()==true
            || street.isEmpty()==true || place.isEmpty()==true || 
            date.isEmpty() == true || krk.isEmpty()== true || krknr.isEmpty()
            == true || tel.isEmpty() == true){
      JOptionPane.showMessageDialog(null, "Es sind noch nicht alle Felder "
      + "ausgefuellt",
      "Fehler!", JOptionPane.DEFAULT_OPTION);
      
    }
    
    else{
    
    try {
      query.patientAnlegen(Vname, Name, street, pLZ, place, date, krk, krknr,
              tel);
    } catch (SQLException ex) {
      Logger.getLogger(AnmeldekraftForm.class.getName()).log(Level.SEVERE, 
              null, ex);
    }
    
    }
    
  }//GEN-LAST:event_Patient_anlegenActionPerformed

  private void kknrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kknrActionPerformed
            // TODO add your handling code here:
  }//GEN-LAST:event_kknrActionPerformed

  private void NachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NachnameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_NachnameActionPerformed

  private void AbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbbrechenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_AbbrechenActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Abbrechen;
  private javax.swing.JButton KKNR_pruefen;
  private javax.swing.JTextField Nachname;
  private javax.swing.JButton Patient_anlegen;
  private javax.swing.JTextField Strasse;
  private javax.swing.JTextField Telefon;
  private javax.swing.JTextField Vorname;
  private javax.swing.JTextField birthday;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JTextField kknr;
  private javax.swing.JTextField krankenkasse;
  private javax.swing.JLabel krankenkasse_label;
  private javax.swing.JTextField ort;
  private javax.swing.JTextField plz;
  // End of variables declaration//GEN-END:variables
}
