/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package notaufnahmedb;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jens
 */
public class LoginForm extends javax.swing.JFrame {

  /**
   * Creates new form LoginForm
   */
  
   private DBConnectionManager dBConnection;
   Connection dbcon;
   Queries query;
   AnmeldekraftForm anmeldekraft;
  
  
  public LoginForm(DBConnectionManager dBConnection) throws SQLException {
    initComponents();
    this.dBConnection = dBConnection;
    this.query = new Queries(dBConnection);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPasswordField = new javax.swing.JPasswordField();
    LoginName = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    Abbrechen = new javax.swing.JButton();
    Anmelden = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPasswordField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jPasswordFieldActionPerformed(evt);
      }
    });

    LoginName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoginNameActionPerformed(evt);
      }
    });

    jLabel1.setText("Benutzername:");

    jLabel2.setText("Kennwort:");

    Abbrechen.setText("Abbrechen");
    Abbrechen.setActionCommand("Abbrechen Button");
    Abbrechen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AbbrechenActionPerformed(evt);
      }
    });

    Anmelden.setText("OK");
    Anmelden.setActionCommand("OK Button");
    Anmelden.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AnmeldenActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
    jLabel3.setText("Notaufnahme InformationsSystem");

    jLabel4.setText("Anmelden als:");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anmeldekraft", "Arzt", "Assistent" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel4))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Anmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Abbrechen))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(LoginName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
          .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(66, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addGap(51, 51, 51)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Anmelden)
          .addComponent(Abbrechen))
        .addGap(59, 59, 59))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void LoginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_LoginNameActionPerformed

  private void AbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbbrechenActionPerformed
    System.exit(0);
  }//GEN-LAST:event_AbbrechenActionPerformed

  private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jPasswordFieldActionPerformed
  
  /*
   *  In dieser Methode wird das Passwort ueberprueft! 
   */
  
  private void AnmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnmeldenActionPerformed
    
    String username = LoginName.getText();
    String password = jPasswordField.getSelectedText();
    try {
      if (password == this.query.checkPW(username));
      {
        anmeldekraft = new AnmeldekraftForm(dBConnection);
        anmeldekraft.setLocationRelativeTo(null);
        anmeldekraft.setVisible(true);
      }
     
    } catch (SQLException ex) {
      Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
      
      Object[] options = { "OK", "CANCEL" };
      JOptionPane.showOptionDialog(null, "Click OK to continue", "falsches PW",
      JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
      null, options, options[0]);
    }
       
  
      

    
  }//GEN-LAST:event_AnmeldenActionPerformed



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Abbrechen;
  private javax.swing.JButton Anmelden;
  private javax.swing.JTextField LoginName;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPasswordField jPasswordField;
  // End of variables declaration//GEN-END:variables
}
